---
# tasks file for gerrit

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: gerrit

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: gerrit

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: gerrit

- name: Create Gerrit installation directory
  file: >
    path=/opt/gerrit
    owner=root
    group=root
    mode=0755
    state=directory
  tags: gerrit

- name: Download Gerrit
  get_url: >
    url=https://gerrit-releases.storage.googleapis.com/gerrit-{{ gerrit_version }}.war
    dest=/opt/gerrit/gerrit-{{ gerrit_version }}.war
    sha256sum={{ gerrit_sha256sum }}
  tags: gerrit

- name: Create Gerrit symlink
  file: >
    src=/opt/gerrit/gerrit-{{ gerrit_version }}.war
    dest=/opt/gerrit/gerrit.war
    owner=root
    group=root
    state=link
  tags: gerrit

- name: Create Gerrit group
  group: >
    name={{ gerrit_group }}
    system=yes
    state=present
  tags: gerrit

- name: Create Gerrit user
  user: >
    name={{ gerrit_user }}
    comment='Gerrit user'
    home={{ gerrit_site_dir }}
    group={{ gerrit_group }}
    system=yes
    state=present
  tags: gerrit

- name: Initialize Gerrit
  sudo: yes
  sudo_user: "{{ gerrit_user }}"
  command: java -jar /opt/gerrit/gerrit.war init --batch --no-auto-start -d {{ gerrit_site_dir }}
  args:
    creates: "{{ gerrit_site_dir }}/bin"
  tags: gerrit
