---
# tasks file for gerrit

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: gerrit

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: gerrit

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: gerrit

- name: Create Gerrit installation directory
  file: >
    path=/opt/gerrit
    owner=root
    group=root
    mode=0755
    state=directory
  tags: gerrit

- name: Download Gerrit
  get_url: >
    url=https://gerrit-releases.storage.googleapis.com/gerrit-{{ gerrit_version }}.war
    dest=/opt/gerrit/gerrit-{{ gerrit_version }}.war
    sha256sum={{ gerrit_sha256sum }}
  tags: gerrit

- name: Create Gerrit symlink
  file: >
    src=/opt/gerrit/gerrit-{{ gerrit_version }}.war
    dest=/opt/gerrit/gerrit.war
    owner=root
    group=root
    state=link
  tags: gerrit

- name: Create Gerrit group
  group: >
    name={{ gerrit_group }}
    system=yes
    state=present
  tags: gerrit

- name: Create Gerrit user
  user: >
    name={{ gerrit_user }}
    comment='Gerrit user'
    home={{ gerrit_site_dir }}
    group={{ gerrit_group }}
    system=yes
    state=present
  tags: gerrit

- name: Initialize Gerrit
  sudo: yes
  sudo_user: "{{ gerrit_user }}"
  command: java -jar /opt/gerrit/gerrit.war init --batch --no-auto-start -d {{ gerrit_site_dir }}
  args:
    creates: "{{ gerrit_site_dir }}/bin"
  tags: gerrit

- name: Create Gerrit defaults file
  template: >
    src=gerritcodereview.j2
    dest=/etc/default/gerritcodereview
    owner=root
    group=root
    mode=0644
  tags: gerrit

- name: Create Gerrit configuration file
  template: >
    src=gerrit.config.j2
    dest={{ gerrit_site_dir }}/etc/gerrit.config
    owner={{ gerrit_user }}
    group={{ gerrit_group }}
    mode=0644
  tags: gerrit

- name: Create Gerrit secure configuration file
  template: >
    src=secure.config.j2
    dest={{ gerrit_site_dir }}/etc/secure.config
    owner={{ gerrit_user }}
    group={{ gerrit_group }}
    mode=0600
  tags: gerrit

- name: Create Gerrit init file
  template: >
    src=gerrit.sh.j2
    dest={{ gerrit_site_dir }}/bin/gerrit.sh
    owner={{ gerrit_user }}
    group={{ gerrit_group }}
    mode=0755
  tags: gerrit

- name: Create Gerrit init file link
  file: >
    src={{ gerrit_site_dir }}/bin/gerrit.sh
    dest=/etc/init.d/gerrit
    state=link
  tags: gerrit
